# Generated by Django 3.1.7 on 2021-03-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcart',
            name='price',
            field=models.FloatField(default=10000, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='productcart',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='quantity'),
        ),
    ]
