# Generated by Django 3.1.7 on 2021-04-02 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210402_0209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='is_current_cart',
        ),
    ]
