# Generated by Django 3.1.7 on 2021-04-02 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_cart_is_current_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcart',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='quantity'),
        ),
    ]
