# Generated by Django 3.1.7 on 2021-04-02 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210402_0216'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCart',
            new_name='CartDetail',
        ),
    ]
