# Generated by Django 3.1.7 on 2021-03-18 16:15

from django.db import migrations, models
import register.models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20210318_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img_url',
            field=models.FileField(default='default.jpg', max_length=255, upload_to=register.models.custom_media_path),
        ),
    ]
